### ISSUE TITLE
Module Broken with Ansible Automation Platform 2.3

### ISSUE THREAD

**Issue by mhill8992** [asagage/orion-node-manage#7]
Due to how this module is written, I don't believe it works well with AAP since you have it configured to use `local_action:` rather than `delegate_to:` I've tried adjusting the tasks to use `delegate_to`, but am receiving syntax errors, so I'm unsure if maybe something in the python code may be conflicting with the changes I've made, but I'm not fluent enough in Python to tell.

**Comment by mhill8992** [comment]
For example, previously my tasks looked like below:

```
- name: unmanage in solarwinds
  local_action:
    module: orion_node_manage
    hostname: "{{ orion_host }}"
    username: "{{ orion_user }}"
    password: "{{ orion_pass }}"
    dns_name: "{{ inventory_hostname }}"
    state: unmanaged
    is_relative: "{{ orion_unmanage_is_relative }}"
    unmanage_until: "{{ orion_unmanage_until }}"

```

I have changed them to look like the below, but for some reason ansible isn't liking the change:

```
- name: unmanage in solarwinds
    orion-node-manage:
      hostname: "{{ orion_host }}"
      username: "{{ orion_user }}"
      password: "{{ orion_pass }}"
      dns_name: "{{ inventory_hostname }}"
      state: unmanaged
      is_relative: "{{ orion_unmanage_is_relative }}"
      unmanage_until: "{{ orion_unmanage_until }}"
  delegate_to: ansible.server.domain
```
